[ UPDATE ] update intl for flutter 3.22 release
hnvn/flutter_pattern_formatter pull request #30
Opened 2024-05-15 12:07 UTC by MahdiForughi

2024-05-15 12:20 UTC, ylruiz requested changes
Nice you went ahead, I was about to create the PR as well 'cause I also need this to upgrade the flutter version :)

2024-05-15 12:20 UTC, ylruiz commented on example/ios/Flutter/flutter_export_environment.sh
I think this file should be excluded from the changes.

2024-05-20 13:15 UTC, JaxBrachetti approved these changes

2024-05-20 14:21 UTC, hnvn commented
@MahdiForughi , can you check the unit test?

2024-05-20 20:54 UTC, closed without merging